services:
  angular-host:
    build:
      context: ./angular-host
    container_name: angular-host
    ports:
      - "4200:80"
    depends_on:
      - angular-mfe1
      - angular-mfe2
      - react-mfe-props
      - react-mfe-window
      - react-mfe-window-collision
      - vue-mfe
      - vue-mfe-window

  angular-mfe1:
    build:
      context: ./angular-mfe
      args:
        MFE_NAME: mfe1
    container_name: angular-mfe1
    ports:
      - "4201:80"

  angular-mfe2:
    build:
      context: ./angular-mfe
      args:
        MFE_NAME: mfe2
    container_name: angular-mfe2
    ports:
      - "4202:80"

  react-mfe-props:
    build:
      context: ./react-mfe
      args:
        REMOTE_TARGET: props
    container_name: react-mfe-props
    ports:
      - "4300:80"

  react-mfe-window:
    build:
      context: ./react-mfe
      args:
        REMOTE_TARGET: window
    container_name: react-mfe-window
    ports:
      - "4301:80"

  react-mfe-window-collision:
    build:
      context: ./react-mfe
      args:
        REMOTE_TARGET: window-collision
    container_name: react-mfe-window-collision
    ports:
      - "4303:80"

  vue-mfe:
    build:
      context: ./vue-mfe
      args:
        REMOTE_TARGET: props
    container_name: vue-mfe
    ports:
      - "4302:80"

  vue-mfe-window:
    build:
      context: ./vue-mfe
      args:
        REMOTE_TARGET: window
    container_name: vue-mfe-window
    ports:
      - "4304:80"
